"""Generate Torfast.app and the "Open Torfast" Quick Action.

The app is a thin launcher bundle: clicking it (Dock, Spotlight,
Launchpad) runs `torfast open`, so the themed Tor Browser appears over
the warm managed Tor with no terminal involved. The Quick Action is an
Automator service so a global keyboard shortcut can summon the browser
from anywhere (System Settings → Keyboard → Keyboard Shortcuts →
Services → General → Open Torfast).

Plist and workflow files are written as literal text on purpose: this
machine's python has a broken pyexpat, so nothing here may depend on xml
parsers.
"""

from __future__ import annotations

import os
import shutil
import sys
import tempfile
from pathlib import Path

from .app_icon import build_icns

REPO_ROOT = Path(__file__).resolve().parents[1]
APP_NAME = "Torfast"
BUNDLE_IDENTIFIER = "org.torfast.launcher"
QUICK_ACTION_NAME = "Open Torfast"
DEFAULT_INSTALL_ROOTS = (
    Path("/Applications"),
    Path.home() / "Applications",
)
SERVICES_DIR = Path.home() / "Library" / "Services"
SHORTCUT_BINDING_HINT = (
    "System Settings → Keyboard → Keyboard Shortcuts → Services → General "
    f"→ {QUICK_ACTION_NAME}"
)

INFO_PLIST_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>torfast</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>{identifier}</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>{name}</string>
	<key>CFBundleDisplayName</key>
	<string>{name}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>{version}</string>
	<key>CFBundleVersion</key>
	<string>{version}</string>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
"""

LAUNCHER_SCRIPT_TEMPLATE = """\
#!/bin/zsh
# Generated by `torfast install-app`; regenerate rather than editing.
# Behaves like a normal browser app: click while open focuses the window,
# click while opening is a no-op, otherwise the themed Tor Browser opens
# over the warm managed Tor. The repo root is baked in so torfast imports
# without a pip install.
# the [b]racket trick keeps these patterns from matching any process that
# merely mentions them (including this script and pgrep itself)
BROWSER_PROFILE="{repo_root}/tmp/torfast-browser/browser-profile"
if pgrep -f "[M]acOS/firefox.*$BROWSER_PROFILE" >/dev/null 2>&1; then
  /usr/bin/osascript -e 'tell application "System Events" to set frontmost of (first process whose name is "firefox") to true' >/dev/null 2>&1
  exit 0
fi
if pgrep -f "[-]m torfast open" >/dev/null 2>&1; then
  /usr/bin/osascript -e 'display notification "Already opening — Tor is warming up." with title "Torfast"' >/dev/null 2>&1
  exit 0
fi
/usr/bin/osascript -e 'display notification "Opening the private browser…" with title "Torfast"' >/dev/null 2>&1
LOG="$HOME/Library/Logs/torfast-app.log"
mkdir -p "$HOME/Library/Logs"
(
  cd "{repo_root}" || exit 1
{browser_env}
  "{python}" -m torfast open --json >> "$LOG" 2>&1
  status=$?
  if [ $status -ne 0 ]; then
    /usr/bin/osascript -e "display notification \\"torfast open failed (exit $status) — see torfast-app.log\\" with title \\"Torfast\\"" >/dev/null 2>&1
  fi
) &!
exit 0
"""

SERVICE_INFO_PLIST = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSServices</key>
	<array>
		<dict>
			<key>NSBackgroundColorName</key>
			<string>background</string>
			<key>NSIconName</key>
			<string>NSTouchBarBookmarksTemplate</string>
			<key>NSMenuItem</key>
			<dict>
				<key>default</key>
				<string>{service_name}</string>
			</dict>
			<key>NSMessage</key>
			<string>runWorkflowAsService</string>
		</dict>
	</array>
</dict>
</plist>
"""

SERVICE_DOCUMENT_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AMApplicationBuild</key>
	<string>528</string>
	<key>AMApplicationVersion</key>
	<string>2.10</string>
	<key>AMDocumentVersion</key>
	<string>2</string>
	<key>actions</key>
	<array>
		<dict>
			<key>action</key>
			<dict>
				<key>AMAccepts</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Optional</key>
					<true/>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>AMActionVersion</key>
				<string>2.0.3</string>
				<key>AMParameterProperties</key>
				<dict>
					<key>COMMAND_STRING</key>
					<dict/>
					<key>CheckedForUserDefaultShell</key>
					<dict/>
					<key>inputMethod</key>
					<dict/>
					<key>shell</key>
					<dict/>
					<key>source</key>
					<dict/>
				</dict>
				<key>AMProvides</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>ActionBundlePath</key>
				<string>/System/Library/Automator/Run Shell Script.action</string>
				<key>ActionName</key>
				<string>Run Shell Script</string>
				<key>ActionParameters</key>
				<dict>
					<key>COMMAND_STRING</key>
					<string>{command}</string>
					<key>CheckedForUserDefaultShell</key>
					<true/>
					<key>inputMethod</key>
					<integer>1</integer>
					<key>shell</key>
					<string>/bin/zsh</string>
					<key>source</key>
					<string></string>
				</dict>
				<key>BundleIdentifier</key>
				<string>com.apple.RunShellScript</string>
				<key>CFBundleVersion</key>
				<string>2.0.3</string>
				<key>CanShowSelectedItemsWhenRun</key>
				<false/>
				<key>CanShowWhenRun</key>
				<true/>
				<key>Category</key>
				<array>
					<string>AMCategoryUtilities</string>
				</array>
				<key>Class Name</key>
				<string>RunShellScriptAction</string>
				<key>InputUUID</key>
				<string>6E4F9A21-0E0B-4E6D-9C40-7A2D6C1B21AA</string>
				<key>Keywords</key>
				<array>
					<string>Shell</string>
					<string>Script</string>
					<string>Command</string>
					<string>Run</string>
					<string>Unix</string>
				</array>
				<key>OutputUUID</key>
				<string>5B1C2D0F-8C7E-4A2B-9D3E-1F0A2B3C4D5E</string>
				<key>UUID</key>
				<string>A0B1C2D3-E4F5-4678-9ABC-DEF012345678</string>
				<key>UnlocalizedApplications</key>
				<array>
					<string>Automator</string>
				</array>
				<key>arguments</key>
				<dict>
					<key>0</key>
					<dict>
						<key>default value</key>
						<integer>0</integer>
						<key>name</key>
						<string>inputMethod</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>0</string>
					</dict>
				</dict>
				<key>isViewVisible</key>
				<integer>1</integer>
				<key>location</key>
				<string>309.000000:253.000000</string>
				<key>nibPath</key>
				<string>/System/Library/Automator/Run Shell Script.action/Contents/Resources/Base.lproj/main.nib</string>
			</dict>
			<key>isViewVisible</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>connectors</key>
	<dict/>
	<key>workflowMetaData</key>
	<dict>
		<key>applicationBundleIDsByPath</key>
		<dict/>
		<key>applicationPaths</key>
		<array/>
		<key>inputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>outputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>presentationMode</key>
		<integer>11</integer>
		<key>processesInput</key>
		<false/>
		<key>serviceInputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>serviceOutputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>serviceProcessesInput</key>
		<false/>
		<key>systemImageName</key>
		<string>NSTouchBarBookmarksTemplate</string>
		<key>useAutomaticInputType</key>
		<false/>
		<key>workflowTypeIdentifier</key>
		<string>com.apple.Automator.servicesMenu</string>
	</dict>
</dict>
</plist>
"""


def default_install_root() -> Path:
    for candidate in DEFAULT_INSTALL_ROOTS:
        if candidate.is_dir() and os.access(candidate, os.W_OK):
            return candidate
    return DEFAULT_INSTALL_ROOTS[-1]


def install_app(
    *,
    dest_root: Path | None = None,
    python_executable: str | None = None,
    repo_root: Path | None = None,
    version: str = "0.1.0",
    force: bool = False,
    include_summon_service: bool = True,
    services_dir: Path | None = None,
    include_icon: bool = True,
    browser_bin: str | None = None,
) -> dict[str, object]:
    root = Path(dest_root) if dest_root is not None else default_install_root()
    python = python_executable or sys.executable
    resolved_repo_root = Path(repo_root) if repo_root is not None else REPO_ROOT
    app_path = root / f"{APP_NAME}.app"
    report: dict[str, object] = {
        "ok": True,
        "app_path": str(app_path),
        "python": python,
        "repo_root": str(resolved_repo_root),
    }

    if app_path.exists():
        if not force:
            report.update(
                {
                    "ok": False,
                    "reason": f"{app_path} already exists; pass --force to replace it",
                }
            )
            return report
        shutil.rmtree(app_path)

    contents = app_path / "Contents"
    macos_dir = contents / "MacOS"
    resources_dir = contents / "Resources"
    macos_dir.mkdir(parents=True)
    resources_dir.mkdir(parents=True)

    (contents / "Info.plist").write_text(
        INFO_PLIST_TEMPLATE.format(
            identifier=BUNDLE_IDENTIFIER,
            name=APP_NAME,
            version=version,
        ),
        encoding="utf-8",
    )
    browser_env = ""
    if browser_bin:
        browser_env = f'  export TORFAST_BROWSER_BIN="{browser_bin}"'
        report["browser_bin"] = browser_bin
    launcher = macos_dir / "torfast"
    launcher.write_text(
        LAUNCHER_SCRIPT_TEMPLATE.format(
            python=python,
            repo_root=resolved_repo_root,
            browser_env=browser_env,
        ),
        encoding="utf-8",
    )
    launcher.chmod(0o755)

    if include_icon:
        with tempfile.TemporaryDirectory() as work:
            report["icon"] = build_icns(resources_dir / "AppIcon.icns", Path(work))
    else:
        report["icon"] = {"ok": True, "skipped": True, "reason": "disabled"}

    if include_summon_service:
        report["summon_service"] = install_summon_service(
            app_path=app_path,
            services_dir=services_dir,
        )
        report["shortcut_binding_hint"] = SHORTCUT_BINDING_HINT
    else:
        report["summon_service"] = {
            "ok": True,
            "skipped": True,
            "reason": "disabled by flag",
        }
    return report


def install_summon_service(
    *,
    app_path: Path,
    services_dir: Path | None = None,
) -> dict[str, object]:
    target_dir = services_dir if services_dir is not None else SERVICES_DIR
    workflow = target_dir / f"{QUICK_ACTION_NAME}.workflow"
    contents = workflow / "Contents"
    report: dict[str, object] = {"ok": True, "workflow_path": str(workflow)}
    try:
        if workflow.exists():
            shutil.rmtree(workflow)
        contents.mkdir(parents=True)
        (contents / "Info.plist").write_text(
            SERVICE_INFO_PLIST.format(service_name=QUICK_ACTION_NAME),
            encoding="utf-8",
        )
        # The service goes through the app so focus/relaunch behavior stays
        # in one place, and `open` returns immediately so the service never
        # shows as still running.
        command = f'/usr/bin/open "{app_path}"'
        (contents / "document.wflow").write_text(
            SERVICE_DOCUMENT_TEMPLATE.format(command=command),
            encoding="utf-8",
        )
    except OSError as exc:
        report.update({"ok": False, "reason": str(exc)})
    return report
